# Generated by Django 5.2.17 on 2026-08-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionjob',
            name='progress',
            field=models.FloatField(default=0.0, help_text='Percent (0-100) of total audio duration transcribed so far.'),
        ),
    ]
