# Generated by Django 5.2.17 on 2026-08-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0002_transcriptionjob_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionjob',
            name='speaker_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of distinct speakers to diarize into. Empty means no diarization.', null=True),
        ),
    ]
